language: node_js
# Using node 8.10 since now currently only supports 8.10
node_js:
  - "8.10"
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - "node_modules"
    - ~/.cache

install:
  - yarn global add lerna codecov
  - yarn
  - lerna bootstrap

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: yarn test && codecov
    - name: "Integration Tests"
      script: yarn integration:ci
