language: node_js
node_js:
  - "10.12.0"

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn global add lerna codecov
  - yarn
  - lerna bootstrap

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: yarn test && codecov
    # TODO: FOR NOW DEACTIVATED: runs out of memory in CI
    # - name: "Integration Tests"
    #   script: yarn integration:ci
